GET http://localhost:3000


###
POST http://localhost:3000/signup/
content-type : application/json

{

    "username" : "gargsgawafwafafwafwsni",
    "password" : "Gan@"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
     "username" : "Ganesh Naidu",
    "password" : "ganesh"
}

###
POST http://localhost:3000/getAllNotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaCBOYWlkdSIsImlhdCI6MTcyMTMzMjE1OX0.8J_LmZDHF1-_NC4jIVDDO9bX_GvEhOQjzqQYAYtcjhs



{
    "userId" : "22"
}

###
POST http://localhost:3000/addNote 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaCBOYWlkdSIsImlhdCI6MTcyMTMzMjE1OX0.8J_LmZDHF1-_NC4jIVDDO9bX_GvEhOQjzqQYAYtcjhs

{
   "noteTitle": "new",
    "desp" : "i createfafafaed a new note",
    "userId" : "47"
}

###
DELETE http://localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaCBOYWlkdSIsImlhdCI6MTcyMTMzMjE1OX0.8J_LmZDHF1-_NC4jIVDDO9bX_GvEhOQjzqQYAYtcjhs

{
    "noteId" : "1",
    "noteTitle": "new",
    "desp" : "i createfafafaed a new note",
    "userId" : "47"
}


###
GET http://localhost:3000/trash?userId=47
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaCBOYWlkdSIsImlhdCI6MTcyMTMzMjE1OX0.8J_LmZDHF1-_NC4jIVDDO9bX_GvEhOQjzqQYAYtcjhs

###
POST http://localhost:3000/trash 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaCBOYWlkdSIsImlhdCI6MTcyMTMzMjE1OX0.8J_LmZDHF1-_NC4jIVDDO9bX_GvEhOQjzqQYAYtcjhs

{
    "userId" : "47"
}