GET http://localhost:3000


###
POST http://localhost:3000/signup/
content-type : application/json

{

    "username" : "gargsgawafwafafwafwsni",
    "password" : "Gan@"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
     "username" : "GaneshNaidu",
    "password" : "Gan@117"
}